name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t rizkyalde7/uas_pemrog3 .

    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.Kulkaslama1 }} | docker login -u ${{ secrets.rizkyalde7 }} --password-stdin
        docker push rizkyalde7/uas_pemrog3
